//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMISentinelPrime.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMIModelContainer : DbContext
    {
        public CMIModelContainer()
            : base("name=CMIModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMI> CMISet { get; set; }
        public virtual DbSet<Objective> ObjectiveSet { get; set; }
        public virtual DbSet<Perspective> PerspectiveSet { get; set; }
        public virtual DbSet<Indicator> IndicatorSet { get; set; }
        public virtual DbSet<MetricType> MetricTypeSet { get; set; }
        public virtual DbSet<DataIndicator> DataIndicatorSet { get; set; }
        public virtual DbSet<Target> TargetSet { get; set; }
    }
}
