//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMISentinelPrime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objective
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objective()
        {
            this.Indicator = new HashSet<Indicator>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Metric { get; set; }
        public decimal Weighting { get; set; }
        public int CMIId { get; set; }
        public int PerspectiveId { get; set; }
    
        public virtual CMI CMI { get; set; }
        public virtual Perspective Perspective { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicator> Indicator { get; set; }
    }
}
