//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMISentinelPrime.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal ExpectedValue { get; set; }
        public System.DateTime DeadlineDate { get; set; }
        public int IndicatorId { get; set; }
    
        public virtual Indicator Indicator { get; set; }
    }
}
